server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_DB_USERNAME:root}
    password: ${POSTGRES_DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration # 기본값
  sql:
    init:
      platform: postgres

#디비 유저만들어서 yml 설정하고 jpa랑 드라이버 깔고 넵
# jpa 기본설정 << 완성되면 공유받기로 알겠습니다 감사해용